<?php

/**
 * @var int     $id
 * @var string  $title
 * @var string  $feedLinkHtml
 * @var string  $datetime
 * @var string  $favoriteButtonHtml
 * @var string  $unreadButtonHtml
 * @var string  $externalLinkHtml
 * @var string  $collapseButtonHtml
 * @var string  $sanitizedContent
 */

use Kniebes\SimpleRssReader\Util\Html;

$actions = $unreadButtonHtml . $favoriteButtonHtml . $externalLinkHtml . $collapseButtonHtml;

?>
<article class="expanded" data-post-id="<?= $id ?>">
    <div class="title"><?= Html::escape($title) ?></div>
    <div class="feed"><?= $feedLinkHtml ?></div>
    <div class="datetime"><?= Html::escape($datetime) ?></div>
    <div class="actions"><?= $actions ?></div>
    <div class="content"><?= $sanitizedContent ?></div>
    <div class="footer"><?= $actions ?></div>
</article>
